import React from 'react';
import {AbsoluteFill,Audio,Img,Sequence,interpolate,spring,staticFile,useCurrentFrame,useVideoConfig} from 'remotion';

const FPS=30,SOURCE_BEAT0=.015949,OUTPUT_AUDIO_OFFSET=.039,BEAT_INTERVAL=.461549;
const beatF=(n:number)=>Math.round((SOURCE_BEAT0+OUTPUT_AUDIO_OFFSET+n*BEAT_INTERVAL)*FPS);
const B=Array.from({length:66},(_,i)=>beatF(i));
const C={bg:'#050b0a',ink:'#f3f7f4',muted:'#93aaa5',cyan:'#62f6e9',teal:'#13bdb1',panel:'#0e1a18',line:'#24423d',cream:'#eef4ef',dark:'#09100f',orange:'#ff7657',yellow:'#ffd166'};
const clamp={extrapolateLeft:'clamp',extrapolateRight:'clamp'} as const;
const map=(f:number,a:number,b:number,x=0,y=1)=>interpolate(f,[a,b],[x,y],clamp);
const out=(v:number)=>1-Math.pow(1-v,4);
const hash=(n:number)=>{const x=Math.sin(n*12.9898)*43758.5453;return x-Math.floor(x)};

const Logo:React.FC<{size:number}>=({size})=><div style={{width:size,height:size,borderRadius:size*.12,overflow:'hidden',background:C.cream}}><Img src={staticFile('locastra-icon.png')} style={{width:'100%',height:'100%',display:'block'}}/></div>;
const BrandBug:React.FC<{vertical:boolean;invert?:boolean}>=({vertical,invert})=><div style={{position:'absolute',top:vertical?130:38,left:vertical?62:64,display:'flex',alignItems:'center',gap:15,zIndex:20}}><Logo size={vertical?50:44}/><div style={{font:`800 ${vertical?32:28}px/1 "Segoe UI Variable",sans-serif`,letterSpacing:1.5,color:invert?C.dark:C.ink}}>LOCASTRA</div></div>;
const Scene:React.FC<{vertical:boolean;light?:boolean;children:React.ReactNode}>=({vertical,light,children})=><AbsoluteFill style={{overflow:'hidden',background:light?C.cream:C.bg,color:light?C.dark:C.ink}}><AbsoluteFill style={{opacity:light?.55:.35,backgroundImage:`linear-gradient(${light?'#123b3520':'#62f6e912'} 1px,transparent 1px),linear-gradient(90deg,${light?'#123b3520':'#62f6e912'} 1px,transparent 1px)`,backgroundSize:vertical?'48px 48px':'64px 64px'}}/><BrandBug vertical={vertical} invert={light}/><div style={{position:'absolute',inset:vertical?'95px 110px 0 0':'0'}}>{children}</div></AbsoluteFill>;
const Big:React.FC<{vertical:boolean;children:React.ReactNode;size?:number;align?:'left'|'center';color?:string}>=({vertical,children,size,align='left',color})=><div style={{font:`900 ${size??(vertical?106:112)}px/.98 "Segoe UI Variable","Microsoft YaHei",sans-serif`,letterSpacing:-4,color,textAlign:align}}>{children}</div>;
const Kicker:React.FC<{vertical:boolean;children:React.ReactNode;color?:string}>=({vertical,children,color=C.cyan})=><div style={{font:`800 ${vertical?42:32}px/1 Cascadia Code,Consolas,monospace`,letterSpacing:vertical?4:3,color}}>{children}</div>;
const Pill:React.FC<{children:React.ReactNode;accent?:boolean;vertical:boolean;light?:boolean}>=({children,accent,vertical,light})=><div style={{padding:vertical?'13px 20px':'10px 18px',borderRadius:999,border:`1px solid ${accent?C.teal:light?'#bacbc6':C.line}`,background:accent?C.cyan:light?'#ffffffa8':'#0e1a18dc',color:accent?C.dark:light?'#2d4742':C.muted,font:`750 ${vertical?32:28}px/1 "Segoe UI Variable","Microsoft YaHei",sans-serif`,whiteSpace:'nowrap'}}>{children}</div>;

const Hook:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame();const cuts=[{from:0,to:9,word:'命令行？',sub:'环境 · 参数 · 端口',color:C.orange},{from:9,to:18,word:'镜像？',sub:'超时 · 断流 · 重试',color:C.yellow},{from:18,to:27,word:'量化？',sub:'Q4 · Q8 · IQ1',color:C.cyan}];if(f>=27&&f<33)return <AbsoluteFill style={{background:'#000'}}/>;const item=cuts.find(x=>f>=x.from&&f<x.to);if(item){const local=f-item.from;return <Scene vertical={vertical}><div style={{position:'absolute',inset:vertical?'0 60px':'0 105px',display:'flex',flexDirection:'column',justifyContent:'center',transform:`scale(${1+local*.004})`}}><Kicker vertical={vertical} color={item.color}>本地 AI 的第一步</Kicker><div style={{marginTop:24}}><Big vertical={vertical} size={vertical?158:180} color={item.color}>{item.word}</Big></div><div style={{marginTop:26,font:`700 ${vertical?34:32}px/1.2 Cascadia Code,monospace`,color:C.muted}}>{item.sub}</div></div><div style={{position:'absolute',right:vertical?-120:60,bottom:vertical?140:60,font:`900 ${vertical?420:380}px/1 Cascadia Code,monospace`,color:`${item.color}12`}}>?</div></Scene>}const t=out(map(f,33,51));return <Scene vertical={vertical}><div style={{position:'absolute',inset:vertical?'0 66px':'0 105px',display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{transform:`translateY(${(1-t)*50}px)`,opacity:t,textAlign:'center'}}><Kicker vertical={vertical} color={C.orange}>STOP WRESTLING WITH SETUP</Kicker><div style={{marginTop:24}}><Big vertical={vertical} align="center" size={vertical?112:136}>本地 AI<br/><span style={{color:C.orange}}>不该这么难</span></Big></div></div></div></Scene>};

const OneEntry:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame();const slam=spring({frame:f,fps:FPS,config:{damping:13,stiffness:155,mass:.7}}),words=['搜索','下载','加载','对话'];return <Scene vertical={vertical} light><div style={{position:'absolute',inset:vertical?'170px 60px 90px':'115px 95px 55px',display:'flex',flexDirection:vertical?'column':'row',alignItems:'center',justifyContent:'center',gap:vertical?55:100}}><div style={{transform:`scale(${.4+slam*.6}) rotate(${(1-slam)*-12}deg)`,boxShadow:'0 40px 120px #13bdb144'}}><Logo size={vertical?245:220}/></div><div style={{maxWidth:vertical?900:1180}}><Kicker vertical={vertical} color={C.teal}>ONE LOCAL AI DESKTOP</Kicker><div style={{marginTop:22}}><Big vertical={vertical} size={vertical?108:130}>一个入口<br/><span style={{color:C.teal}}>全部搞定</span></Big></div><div style={{display:'flex',flexWrap:'wrap',gap:12,marginTop:36}}>{words.map((w,i)=>{const p=spring({frame:f-10-i*4,fps:FPS,config:{damping:16,stiffness:145}});return <div key={w} style={{opacity:p,transform:`translateY(${(1-p)*22}px)`}}><Pill vertical={vertical} light accent={i===3}>{w}</Pill></div>})}</div></div></div></Scene>};

const SourceHub:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),sources=['魔搭 ModelScope','hf-mirror.com','Hugging Face','本地 GGUF'];return <Scene vertical={vertical}><div style={{position:'absolute',inset:vertical?'155px 54px 65px':'110px 80px 55px'}}><Kicker vertical={vertical}>01 · 多源模型入口</Kicker><div style={{display:'grid',gridTemplateColumns:vertical?'1fr':'1.05fr .95fr',gap:vertical?36:80,alignItems:'center',height:'90%'}}><Big vertical={vertical} size={vertical?106:122}>多路入口<br/><span style={{color:C.cyan}}>一处管理</span></Big><div style={{display:'grid',gap:vertical?16:13}}>{sources.map((x,i)=>{const s=spring({frame:f-i*5,fps:FPS,config:{damping:18,stiffness:150}});return <div key={x} style={{height:vertical?104:82,borderRadius:18,border:`1px solid ${i===0?C.teal:C.line}`,background:i===0?'#11312d':C.panel,display:'flex',alignItems:'center',padding:'0 24px',gap:20,transform:`translateX(${(1-s)*120}px)`,opacity:s}}><div style={{width:42,height:42,borderRadius:12,display:'grid',placeItems:'center',background:i===0?C.cyan:'#1c2c29',color:i===0?C.dark:C.muted,font:'800 17px Cascadia Code'}}>{String(i+1).padStart(2,'0')}</div><div style={{font:`750 ${vertical?34:32}px "Segoe UI Variable","Microsoft YaHei"`,color:i===0?C.ink:C.muted}}>{x}</div></div>})}</div></div></div></Scene>};

const Fit:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),scan=map(f,0,48);return <Scene vertical={vertical} light><div style={{position:'absolute',inset:vertical?'155px 58px 60px':'110px 88px 55px'}}><Kicker vertical={vertical} color={C.teal}>02 · 自动硬件适配</Kicker><div style={{display:'grid',gridTemplateColumns:vertical?'1fr':'1fr 1fr',gap:vertical?42:90,alignItems:'center',height:'88%'}}><div><Big vertical={vertical} size={vertical?106:118}>先看电脑<br/>再选模型</Big><div style={{font:`650 ${vertical?36:32}px/1.5 "Segoe UI Variable","Microsoft YaHei"`,color:'#52706a',marginTop:30}}>CPU · 内存 · 显卡 · 显存 · 磁盘</div></div><div style={{position:'relative',height:vertical?610:520,display:'grid',placeItems:'center'}}>{[0,1,2].map(i=><div key={i} style={{position:'absolute',width:(vertical?530:500)-i*100,height:(vertical?530:500)-i*100,borderRadius:'50%',border:`${i===1?3:1}px solid ${i===1?C.teal:'#97b2ac'}`,transform:`rotate(${f*(i===1?.7:-.25)+i*35}deg)`,borderLeftColor:'transparent'}}/>)}<div style={{width:vertical?250:230,height:vertical?250:230,borderRadius:42,background:C.dark,color:C.ink,display:'grid',placeItems:'center',boxShadow:'0 35px 80px #00352d44',transform:`scale(${.93+scan*.07})`}}><div style={{textAlign:'center'}}><div style={{font:`900 ${vertical?48:44}px Cascadia Code`}}>GPU SCAN</div><div style={{color:C.cyan,font:`700 ${vertical?26:22}px "Segoe UI Variable"`,marginTop:12}}>适配结果示例</div></div></div></div></div></div></Scene>};

const Quant:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),options=[['Q4_K_M','平衡推荐'],['Q8_K_XL','高质量'],['IQ1_M','超大模型']];return <Scene vertical={vertical}><div style={{position:'absolute',inset:vertical?'145px 55px 55px':'105px 84px 50px'}}><Kicker vertical={vertical}>03 · 量化推荐</Kicker><div style={{marginTop:vertical?55:34}}><Big vertical={vertical} size={vertical?106:112}>不懂 Q4、Q8？<br/><span style={{color:C.cyan}}>它替你选</span></Big></div><div style={{display:'grid',gridTemplateColumns:vertical?'1fr':'repeat(3,1fr)',gap:20,marginTop:vertical?65:42}}>{options.map((x,i)=>{const q=spring({frame:f-i*6,fps:FPS,config:{damping:14,stiffness:150}});return <div key={x[0]} style={{height:vertical?190:210,borderRadius:26,border:`2px solid ${i===0?C.cyan:C.line}`,background:i===0?'linear-gradient(135deg,#123c36,#0c2420)':C.panel,padding:vertical?'30px 34px':'34px',transform:`translateY(${(1-q)*90}px) rotate(${(1-q)*(i-1)*4}deg)`,opacity:q}}><div style={{font:`900 ${vertical?43:44}px Cascadia Code`,color:i===0?C.cyan:C.ink}}>{x[0]}</div><div style={{font:`700 ${vertical?34:32}px "Segoe UI Variable","Microsoft YaHei"`,color:i===0?C.ink:C.muted,marginTop:18}}>{x[1]}</div>{i===0&&<div style={{marginTop:20,display:'inline-block',padding:'8px 12px',borderRadius:99,background:C.cyan,color:C.dark,font:'800 28px Cascadia Code'}}>AUTO PICK</div>}</div>})}</div></div></Scene>};

const Download:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),progress=Math.min(100,Math.round(map(f,0,30,0,100)));return <Scene vertical={vertical} light><div style={{position:'absolute',inset:vertical?'150px 58px 58px':'108px 88px 55px'}}><Kicker vertical={vertical} color={C.teal}>04 · 国内友好下载</Kicker><div style={{display:'grid',gridTemplateColumns:vertical?'1fr':'1fr 1.15fr',gap:vertical?48:90,alignItems:'center',height:'88%'}}><div><Big vertical={vertical} size={vertical?104:126}>断网？<br/><span style={{color:C.orange}}>接着下。</span></Big><div style={{display:'flex',flexWrap:'wrap',gap:10,marginTop:30}}><Pill vertical={vertical} light>暂停继续</Pill><Pill vertical={vertical} light>自动重试</Pill><Pill vertical={vertical} light>多源切换</Pill></div></div><div style={{background:'#fff',border:'1px solid #bdd0ca',borderRadius:28,padding:vertical?'34px':'38px',boxShadow:'0 35px 90px #173a3422'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{font:`800 ${vertical?36:32}px "Segoe UI Variable"`}}>Qwen3.8-27B.Q8.gguf</div><div style={{font:`650 ${vertical?30:28}px Cascadia Code`,color:'#66817b',marginTop:10}}>自动切换可用来源</div></div><div style={{font:`900 ${vertical?52:48}px Cascadia Code`,color:C.teal}}>{progress}%</div></div><div style={{height:vertical?18:14,borderRadius:99,background:'#dbe7e3',marginTop:32,overflow:'hidden'}}><div style={{width:`${progress}%`,height:'100%',background:`linear-gradient(90deg,${C.teal},${C.cyan})`}}/></div><div style={{display:'flex',justifyContent:'space-between',marginTop:18,font:`700 ${vertical?30:28}px Cascadia Code`,color:'#5a746e'}}><span>HTTP RANGE</span><span>断点续传</span></div></div></div></div></Scene>};

const Accelerate:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame();return <Scene vertical={vertical}><div style={{position:'absolute',inset:vertical?'150px 55px 55px':'108px 85px 54px'}}><Kicker vertical={vertical}>05 · 自动加速</Kicker><div style={{display:'grid',gridTemplateColumns:vertical?'1fr':'1.05fr .95fr',gap:vertical?50:80,alignItems:'center',height:'88%'}}><div><Big vertical={vertical} size={vertical?108:122}>CUDA<br/>Vulkan<br/><span style={{color:C.cyan}}>自动卸载</span></Big></div><div style={{display:'grid',gap:15}}>{['NVIDIA CUDA','AMD / Intel Vulkan','CPU 混合卸载'].map((x,i)=>{const p=spring({frame:f-i*7,fps:FPS,config:{damping:17,stiffness:150}});return <div key={x} style={{height:vertical?112:96,borderRadius:18,border:`1px solid ${i===0?C.cyan:C.line}`,background:i===0?'#10342f':C.panel,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 25px',transform:`translateX(${(1-p)*100}px)`,opacity:p}}><span style={{font:`800 ${vertical?36:32}px "Segoe UI Variable"`,color:i===0?C.cyan:C.ink}}>{x}</span><span style={{font:`800 ${vertical?34:30}px Cascadia Code`,color:C.muted}}>{i===0?'AUTO':'READY'}</span></div>})}</div></div></div></Scene>};

const Privacy:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),lock=spring({frame:f,fps:FPS,config:{damping:12,stiffness:140}});return <Scene vertical={vertical} light><div style={{position:'absolute',inset:0,display:'grid',placeItems:'center'}}><div style={{textAlign:'center',transform:`scale(${.7+lock*.3})`}}><div style={{width:vertical?190:160,height:vertical?190:160,borderRadius:'50%',background:C.dark,display:'grid',placeItems:'center',margin:'0 auto',boxShadow:'0 35px 90px #153e3744'}}><div style={{font:`900 ${vertical?72:64}px/1 sans-serif`,color:C.cyan}}>⌾</div></div><div style={{marginTop:35}}><Kicker vertical={vertical} color={C.teal}>127.0.0.1 · LOCAL ONLY</Kicker></div><div style={{marginTop:22}}><Big vertical={vertical} align="center" size={vertical?108:128}>模型在本机<br/><span style={{color:C.teal}}>内容不出电脑</span></Big></div></div></div></Scene>};

const Quad:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),items=[['流式输出','STREAMING'],['长上下文','LONG CONTEXT'],['助手资料','LOCAL RAG'],['MCP 工具','SAFE MODE']];return <Scene vertical={vertical}><div style={{position:'absolute',inset:vertical?'128px 35px 38px':'86px 45px 34px',display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}>{items.map((x,i)=>{const q=spring({frame:f-i*5,fps:FPS,config:{damping:15,stiffness:160}}),pulse=f<24?1+Math.sin((f-i*4)/5)*.012:1;return <div key={x[0]} style={{borderRadius:24,border:`1px solid ${i===0?C.cyan:C.line}`,background:i%2===0?'#10211e':'#0b1513',padding:vertical?'36px 28px':'30px 34px',display:'flex',flexDirection:'column',justifyContent:'space-between',transform:`scale(${q*pulse})`,opacity:q,overflow:'hidden'}}><div style={{font:`900 ${vertical?43:40}px/1.05 "Segoe UI Variable","Microsoft YaHei"`,color:i===0?C.cyan:C.ink}}>{x[0]}</div><div style={{font:`800 ${vertical?32:30}px Cascadia Code`,color:C.muted}}>{x[1]}</div><div style={{height:7,borderRadius:99,background:C.line,overflow:'hidden'}}><div style={{height:'100%',width:`${map(f,5+i*4,28+i*4,5,92)}%`,background:i===0?C.cyan:C.teal}}/></div></div>})}</div></Scene>};

const Chat:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),q=spring({frame:f,fps:FPS,config:{damping:14,stiffness:145}}),flow=map(f,0,28);return <Scene vertical={vertical} light><div style={{position:'absolute',inset:vertical?'148px 54px 52px':'105px 88px 52px'}}><Kicker vertical={vertical} color={C.teal}>06 · 离线对话</Kicker><div style={{display:'grid',gridTemplateColumns:vertical?'1fr':'1fr 1fr',gap:vertical?45:90,alignItems:'center',height:'88%'}}><div><Big vertical={vertical} size={vertical?108:118}>网络断开<br/><span style={{color:C.teal}}>仍可对话</span></Big><div style={{display:'flex',gap:12,marginTop:30}}><Pill vertical={vertical} light>NETWORK OFF</Pill><Pill vertical={vertical} light accent>LOCAL READY</Pill></div></div><div style={{position:'relative',height:vertical?520:430,display:'grid',placeItems:'center'}}><div style={{position:'absolute',width:vertical?440:400,height:vertical?440:400,borderRadius:'50%',border:'2px solid #b9cec8',transform:`scale(${.82+q*.18})`}}/><div style={{width:vertical?220:200,height:vertical?220:200,borderRadius:48,background:C.dark,display:'grid',placeItems:'center',boxShadow:'0 35px 90px #173a3440'}}><div style={{textAlign:'center'}}><div style={{font:`900 ${vertical?52:48}px Cascadia Code`,color:C.cyan}}>GGUF</div><div style={{font:`800 ${vertical?32:30}px "Segoe UI Variable"`,color:C.ink,marginTop:12}}>本地生成</div></div></div>{Array.from({length:18},(_,i)=>{const a=i/18*Math.PI*2,r=(vertical?260:240)*flow;return <i key={i} style={{position:'absolute',left:'50%',top:'50%',width:i%4===0?14:8,height:i%4===0?14:8,borderRadius:'50%',background:i%4===0?C.teal:'#78968f',transform:`translate(calc(-50% + ${Math.cos(a)*r}px),calc(-50% + ${Math.sin(a)*r}px))`,opacity:flow}}/>})}</div></div></div></Scene>};

const Triple:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),words=[['不登录','NO ACCOUNT'],['不上传','NO CLOUD'],['免费开源','OPEN SOURCE']];return <Scene vertical={vertical}><div style={{position:'absolute',inset:vertical?'145px 50px 55px':'110px 80px 55px'}}><Kicker vertical={vertical}>WHY LOCASTRA</Kicker><div style={{display:'grid',gridTemplateColumns:vertical?'1fr':'repeat(3,1fr)',gap:18,marginTop:vertical?55:45}}>{words.map((x,i)=>{const q=spring({frame:f-i*6,fps:FPS,config:{damping:13,stiffness:170}});return <div key={x[0]} style={{height:vertical?245:460,borderRadius:28,background:i===2?C.cyan:C.panel,border:`1px solid ${i===2?C.cyan:C.line}`,padding:vertical?'34px':'38px',display:'flex',flexDirection:'column',justifyContent:'space-between',transform:`translateY(${(1-q)*140}px)`,opacity:q}}><div style={{font:`900 ${vertical?58:58}px/1 "Segoe UI Variable","Microsoft YaHei"`,color:i===2?C.dark:C.ink}}>{x[0]}</div><div style={{font:`800 ${vertical?32:30}px Cascadia Code`,color:i===2?'#14524b':C.muted}}>{x[1]}</div></div>})}</div></div></Scene>};

const FiveSteps:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),steps=['检测电脑','搜索模型','智能推荐','稳定下载','本地开聊'];return <Scene vertical={vertical} light><div style={{position:'absolute',inset:vertical?'145px 52px 58px':'108px 80px 58px'}}><Kicker vertical={vertical} color={C.teal}>ZERO TERMINAL WORKFLOW</Kicker><div style={{marginTop:28}}><Big vertical={vertical} size={vertical?108:124}>五步完成<br/><span style={{color:C.teal}}>本地 AI 闭环</span></Big></div><div style={{display:'grid',gridTemplateColumns:vertical?'1fr':'repeat(5,1fr)',gap:12,marginTop:vertical?54:44}}>{steps.map((x,i)=>{const q=spring({frame:f-i*4,fps:FPS,config:{damping:16,stiffness:155}});return <div key={x} style={{height:vertical?108:190,borderRadius:20,background:i===4?C.dark:'#fff',border:'1px solid #bed0ca',padding:vertical?'0 26px':'25px',display:'flex',flexDirection:vertical?'row':'column',alignItems:vertical?'center':'flex-start',justifyContent:'space-between',transform:`scale(${.8+q*.2})`,opacity:q}}><div style={{font:`900 ${vertical?38:34}px Cascadia Code`,color:i===4?C.cyan:C.teal}}>{String(i+1).padStart(2,'0')}</div><div style={{font:`800 ${vertical?36:30}px "Segoe UI Variable","Microsoft YaHei"`,color:i===4?C.ink:C.dark}}>{x}</div></div>})}</div></div></Scene>};

const Burst:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),q=spring({frame:f,fps:FPS,config:{damping:11,stiffness:170}});return <Scene vertical={vertical}>{Array.from({length:72},(_,i)=>{const a=hash(i)*Math.PI*2,r=map(f,3,50,20,vertical?650:900),s=5+hash(i+4)*12;return <div key={i} style={{position:'absolute',left:'50%',top:'50%',width:s,height:s,borderRadius:i%3===0?'50%':3,background:i%5===0?C.orange:i%4===0?C.yellow:C.cyan,transform:`translate(${Math.cos(a)*r}px,${Math.sin(a)*r}px) rotate(${f*(i%2?7:-5)}deg)`,opacity:map(f,28,52,1,0)}}/>})}<div style={{position:'absolute',inset:0,display:'grid',placeItems:'center'}}><div style={{textAlign:'center',transform:`scale(${.35+q*.65})`}}><Kicker vertical={vertical} color={C.orange}>VERSION 0.9.0</Kicker><div style={{marginTop:22}}><Big vertical={vertical} align="center" size={vertical?106:138}>为 Windows<br/><span style={{color:C.cyan}}>认真做的本地 AI</span></Big></div></div></div></Scene>};

const Outro:React.FC<{vertical:boolean}>=({vertical})=>{const f=useCurrentFrame(),q=spring({frame:f,fps:FPS,config:{damping:14,stiffness:130}}),url=out(map(f,4,20));return <Scene vertical={vertical} light><div style={{position:'absolute',inset:0,display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{textAlign:'center',transform:`translateY(${(1-q)*40}px)`,opacity:q,maxWidth:vertical?960:1500}}><div style={{display:'flex',justifyContent:'center'}}><Logo size={vertical?190:150}/></div><div style={{font:`900 ${vertical?104:112}px/1 "Segoe UI Variable",sans-serif`,letterSpacing:5,color:C.dark,marginTop:28}}>LOCASTRA</div><div style={{font:`800 ${vertical?52:36}px/1.25 "Segoe UI Variable","Microsoft YaHei",sans-serif`,color:'#526c66',marginTop:18}}>Windows 本地 AI，一步到位</div><div style={{height:2,background:'#c1d0cb',margin:vertical?'42px 40px 32px':'36px 110px 30px',overflow:'hidden'}}><div style={{height:'100%',width:`${url*100}%`,background:C.teal}}/></div><div style={{font:`850 ${vertical?58:37}px/1 Cascadia Code,Consolas,monospace`,color:C.teal,opacity:url,whiteSpace:'nowrap'}}>github.com/Nobel-BY/Locastra</div><div style={{display:'flex',justifyContent:'center',gap:10,marginTop:30,opacity:map(f,18,30)}}><Pill vertical={vertical} light accent>免费下载</Pill><Pill vertical={vertical} light>Windows x64</Pill><Pill vertical={vertical} light>开源</Pill></div></div></div></Scene>};

const SHOTS=[{from:0,to:B[4],node:Hook},{from:B[4],to:B[8],node:OneEntry},{from:B[8],to:B[12],node:SourceHub},{from:B[12],to:B[16],node:Fit},{from:B[16],to:B[20],node:Quant},{from:B[20],to:B[24],node:Download},{from:B[24],to:B[28],node:Accelerate},{from:B[28],to:B[32],node:Privacy},{from:B[32],to:B[36],node:Quad},{from:B[36],to:B[40],node:Chat},{from:B[40],to:B[44],node:Triple},{from:B[44],to:B[48],node:FiveSteps},{from:B[48],to:B[50],node:Burst},{from:B[50],to:900,node:Outro}];
const SFX=[{from:0,duration:35,src:'impact-deep-whoosh.mp3',volume:.24},{from:B[4],duration:40,src:'whoosh-fast.mp3',volume:.17},{from:B[20],duration:40,src:'sweep-metal-quick.mp3',volume:.15},{from:B[28],duration:42,src:'air-zoom-vacuum.mp3',volume:.13},{from:B[40],duration:40,src:'whoosh-fast.mp3',volume:.16},{from:B[48],duration:58,src:'impact-deep-whoosh.mp3',volume:.23},{from:B[50],duration:62,src:'shimmer-sparkle-sweep.mp3',volume:.14}];
const Soundtrack:React.FC=()=><><Audio src={staticFile('audio/cat-walk.mp3')} startFrom={450} volume={f=>Math.min(.48,f/20*.48,(900-f)/45*.48)}/>{SFX.map((s,i)=><Sequence key={i} from={s.from} durationInFrames={s.duration}><Audio src={staticFile(`audio/${s.src}`)} volume={s.volume}/></Sequence>)}</>;
export const LocastraPromo:React.FC<{vertical:boolean}>=({vertical})=>{const {width,height}=useVideoConfig();return <AbsoluteFill style={{width,height,overflow:'hidden'}}>{SHOTS.map((s,i)=>{const Comp=s.node;return <Sequence key={i} from={s.from} durationInFrames={s.to-s.from}><Comp vertical={vertical}/></Sequence>})}<Soundtrack/></AbsoluteFill>};
